# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Accel.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Accel.proto',
  package='Acceleration',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0b\x41\x63\x63\x65l.proto\x12\x0c\x41\x63\x63\x65leration\"x\n\x10\x41\x63\x63\x65lerationData\x12\x12\n\x06millis\x18\x01 \x03(\x03\x42\x02\x10\x01\x12\r\n\x01x\x18\x02 \x03(\x05\x42\x02\x10\x01\x12\r\n\x01y\x18\x03 \x03(\x05\x42\x02\x10\x01\x12\r\n\x01z\x18\x04 \x03(\x05\x42\x02\x10\x01\x12\x11\n\tlongitude\x18\x05 \x01(\x01\x12\x10\n\x08latitude\x18\x06 \x01(\x01\"\xe5\x01\n\tRidePacks\x12+\n\x05packs\x18\x01 \x03(\x0b\x32\x1c.Acceleration.RidePacks.Pack\x1a\xaa\x01\n\x04Pack\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08\x64uration\x18\x02 \x01(\x05\x12\x32\n\x06points\x18\x03 \x03(\x0b\x32\".Acceleration.RidePacks.Pack.Point\x1aN\n\x05Point\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x17\n\x0btransitions\x18\x02 \x03(\x05\x42\x02\x10\x01\x12\x0c\n\x04\x64ist\x18\x03 \x01(\x05\x12\x10\n\x08\x64uration\x18\x04 \x01(\x05\x62\x06proto3')
)




_ACCELERATIONDATA = _descriptor.Descriptor(
  name='AccelerationData',
  full_name='Acceleration.AccelerationData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='millis', full_name='Acceleration.AccelerationData.millis', index=0,
      number=1, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x', full_name='Acceleration.AccelerationData.x', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='Acceleration.AccelerationData.y', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='Acceleration.AccelerationData.z', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='Acceleration.AccelerationData.longitude', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='Acceleration.AccelerationData.latitude', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=149,
)


_RIDEPACKS_PACK_POINT = _descriptor.Descriptor(
  name='Point',
  full_name='Acceleration.RidePacks.Pack.Point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Acceleration.RidePacks.Pack.Point.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='transitions', full_name='Acceleration.RidePacks.Pack.Point.transitions', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dist', full_name='Acceleration.RidePacks.Pack.Point.dist', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='duration', full_name='Acceleration.RidePacks.Pack.Point.duration', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=303,
  serialized_end=381,
)

_RIDEPACKS_PACK = _descriptor.Descriptor(
  name='Pack',
  full_name='Acceleration.RidePacks.Pack',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Acceleration.RidePacks.Pack.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='duration', full_name='Acceleration.RidePacks.Pack.duration', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='points', full_name='Acceleration.RidePacks.Pack.points', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_RIDEPACKS_PACK_POINT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=211,
  serialized_end=381,
)

_RIDEPACKS = _descriptor.Descriptor(
  name='RidePacks',
  full_name='Acceleration.RidePacks',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='packs', full_name='Acceleration.RidePacks.packs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_RIDEPACKS_PACK, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=381,
)

_RIDEPACKS_PACK_POINT.containing_type = _RIDEPACKS_PACK
_RIDEPACKS_PACK.fields_by_name['points'].message_type = _RIDEPACKS_PACK_POINT
_RIDEPACKS_PACK.containing_type = _RIDEPACKS
_RIDEPACKS.fields_by_name['packs'].message_type = _RIDEPACKS_PACK
DESCRIPTOR.message_types_by_name['AccelerationData'] = _ACCELERATIONDATA
DESCRIPTOR.message_types_by_name['RidePacks'] = _RIDEPACKS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AccelerationData = _reflection.GeneratedProtocolMessageType('AccelerationData', (_message.Message,), dict(
  DESCRIPTOR = _ACCELERATIONDATA,
  __module__ = 'Accel_pb2'
  # @@protoc_insertion_point(class_scope:Acceleration.AccelerationData)
  ))
_sym_db.RegisterMessage(AccelerationData)

RidePacks = _reflection.GeneratedProtocolMessageType('RidePacks', (_message.Message,), dict(

  Pack = _reflection.GeneratedProtocolMessageType('Pack', (_message.Message,), dict(

    Point = _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), dict(
      DESCRIPTOR = _RIDEPACKS_PACK_POINT,
      __module__ = 'Accel_pb2'
      # @@protoc_insertion_point(class_scope:Acceleration.RidePacks.Pack.Point)
      ))
    ,
    DESCRIPTOR = _RIDEPACKS_PACK,
    __module__ = 'Accel_pb2'
    # @@protoc_insertion_point(class_scope:Acceleration.RidePacks.Pack)
    ))
  ,
  DESCRIPTOR = _RIDEPACKS,
  __module__ = 'Accel_pb2'
  # @@protoc_insertion_point(class_scope:Acceleration.RidePacks)
  ))
_sym_db.RegisterMessage(RidePacks)
_sym_db.RegisterMessage(RidePacks.Pack)
_sym_db.RegisterMessage(RidePacks.Pack.Point)


_ACCELERATIONDATA.fields_by_name['millis']._options = None
_ACCELERATIONDATA.fields_by_name['x']._options = None
_ACCELERATIONDATA.fields_by_name['y']._options = None
_ACCELERATIONDATA.fields_by_name['z']._options = None
_RIDEPACKS_PACK_POINT.fields_by_name['transitions']._options = None
# @@protoc_insertion_point(module_scope)
